### ISSUE TITLE
Feature-invariant LSTM

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#109]
Here's the pitch: use the feature-invariance notion on an LSTM wiith feature. @bonham79 thinks this is an easy fix.

One question is whether we want to add a new `--arch` flag or just add `--feature_invariant`.

**Comment by kylebgorman** [comment]
It would be the same as the [feature-invariant transformer](https://github.com/CUNY-CL/yoyodyne/blob/28ff0e5bc34a7402332b020599cce8d910079175/yoyodyne/models/modules/transformer.py#L187): 

* the source and features would be concatenated along the length dimension
* there would be a `type embedding` of size 2 x embedding size
* during input embedding, we'd concatenate the type embedding to the ordinary embeddings about the embedding dimension (i.e., making each embedding twice as large) so that source symbols and features symbols have different learned embeddings. 

In fact I think you could probably do this by changing the feature invariant module linked to above to a mix-in called `FeatureInvarianceMixin` and then mixing it in like so:

```python
class FeatureInvariantTransformerEncoder(TransformerEncoder, FeatureInvarianceMixin): ...
class FeatureInvariantLSTMEncoder(LSTMEncoder, FeatureInvarianceMixin): ...
```

**Comment by Adamits** [comment]
We spoke about this offline.

In the `FeatureInvariantTransformerEncoder`, along with a type embedding, we crucially also zero out the positional encoding information. Since this info is naturally encoded in the LSTM recurrence, I am not sure we would do this here in a such a straightforward way (of course, we could encode the LSTM features separately with position-invariant self-attention, and I think some work has preferred this).

Still, I think it could be good to add feature embeddings, and maybe also enable this position invariance, but the semantics of calling it something equivalent to the `FeatureInvariantTransformerEncoder` is a bit confusing IMO. See the paragraph "Feature Invariance" in section 2 of https://aclanthology.org/2021.eacl-main.163.pdf for the Transformer details.

**Comment by kylebgorman** [comment]
Thanks for documenting Adam. Let's close this for now.
