### ISSUE TITLE
Transducer feature embedding

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#12]
[copied from CUNY-CL/abstractness/issues/96]

Transducers make it somewhat difficult to condition generation on features. Makarov & Clematide use a one-hot embedding of features, concatenated itemwise to the input string embeddings, but @bonham79's pilot results suggest this is ineffectual. We can imagine at least a couple other ways to do it:

1. Features could be embedded, combined via mean, and then used to initialize the decoder state.
2. Features could be embedded, combined via mean, and then concatenated itemwise to the input string embeddings.
3. Features could be encoded and this encoding used to initialize the decoder state.
4. Features could be encoded, and then concatenated itemwise to the input strring embeddings.

**Comment by bonham79** [comment]
So just cause it's been a bit, want to clarify 1 and 3. For 3, I can see how the hidden states from an encoder can be passed as initial states to the decoder, which would be pretty nifty thing to try. However, I'm not understanding how that would carry for embeddings. Am I misinterpreting?

**Comment by kylebgorman** [comment]
#1 would constrain the embedding to a certain dimension unless you added some additional layer to reshape them how you wanted. #3 is the interesting case for me anyways---the one most likely to work.

**Comment by bonham79** [comment]
Ran some tests on SIGMORPHON Basque data. Turns out merging 3 and 4 work the best (i.e. pass hidden states to decoder **and** concatenate to each character). Was able to get 91% accuracy with only five epochs of training. (Compared to 89% with just hidden states). I imagine this sorta makes sense, provides global knowledge of features to the whole decoder and local knowledge for each edit.

Outside  that, using embeddings instead of n_hot encoding does second best.

What are we feeling PR wise? Have a flag that allows multiple options or just use the best performing one?

**Comment by kylebgorman** [comment]
I'm fine with just one solution.

How much worse does just using embeddings give us? And are you combining
with mean or what?

**Comment by bonham79** [comment]
Just embeddings gives about 84/85% performance. So the encoding does a fair bit of work.

Embeddings are averaged. Hidden encoding are summed (borrowed from pointer generator.)
