### ISSUE TITLE
Missing init_embeddings in Transformer module

### ISSUE THREAD

**Issue by bonham79** [CUNY-CL/yoyodyne#215]
There's a call to `init_embeddings` in the Transformer invariant feature encoder. That only exists in the model. This should be moved

**Comment by kylebgorman** [comment]
Are you referring to [this](https://github.com/CUNY-CL/yoyodyne/blob/e04fedb940e94132ae729aa9df92251a3003dee4/yoyodyne/models/modules/transformer.py#L227C1-L229C10)? I think you need that; it gives you the additional embedding that distinguishes source from features, which is then concatenated (symbolwise) with the inherited embedding [here](https://github.com/CUNY-CL/yoyodyne/blob/e04fedb940e94132ae729aa9df92251a3003dee4/yoyodyne/models/modules/transformer.py#L254). But I didn't write this; @Adamits can confirm though since this was not my doing.

**Comment by bonham79** [comment]
No, there is a call to `init_embeddings` by `feature_invariant_transformer` to initialize `type_embedding`. That method only exists at the model level. It's not an existing method in modules for inheritance.

**Comment by kylebgorman** [comment]
Please confirm: you are referring to the line I linked to in my earlier comment? Or if not, please link or give a line number.

**Comment by bonham79** [comment]
Yes that's the correct line.

**Comment by kylebgorman** [comment]
Thanks, I see the issue and self-assigning.

**Comment by kylebgorman** [comment]
Closed by #219.
