### ISSUE TITLE
Restarting training

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#6]
[copied from CUNY-CL/abstractness/issues/102]

The PTL training loop attempts to gracefully shut down in response to a Ctrl+C keyboard interrupt. However, simply re-running the same training command restarts training from scratch, with a new version number. This is in contrast to, e.g., FairSeq, which picks up from the last checkpoint.

One suspects this is unpredictable behavior; restarts ought to be programmatically supported.

**This is a blocker for a post-beta release candidate.**

**Comment by Adamits** [comment]
To be clear, we want a CLI option s.t. we can restart from exactly where we left off? I would expect the default behavior to be that it starts a new version from scratch. Is this your expectation too?

**Comment by kylebgorman** [comment]
I am not sure exactly. I think that it starts from scratch was slightly surprising given FairSeq's behavior, which is to continue on from there. But if we don't agree on what's more surprising, let's keep the default behavior as is.

It may be the case that `--train_from` already does what we want, in which case we should just document how to use this in the README (we may want to reference the differential behavior of ours vs. FairSeq's) and then close the issue.

**Comment by Adamits** [comment]
Maybe I should rethink this. So in Fairseq if I start a job with output path `p`, and there is already a model there, by default it continues training from where that model left off? PTL gives us this version_`n` behavior by default, but maybe I should read up on its intended usage.

And for use-cases, let's say I start a run, then realize I have a bug in my training data, used bad hyperparameters, or need to tweak something in the code -- then to rerun from scratch I would either delete the previous output dir so that I overwrite it, or set a new output path? That seems reasonable. Though I am not totally sure which is better.

**Comment by kylebgorman** [comment]
> Maybe I should rethink this. So in Fairseq if I start a job with output path `p`, and there is already a model there, by default it continues training from where that model left off? 

Yes.

I am, on reflection, fine with the current behavior---and just not fighting PTL---I just think we need both behaviors documented (in the README let's say). That seems the simple solution for now.

**Comment by kylebgorman** [comment]
Closed in #34.
