### ISSUE TITLE
Default Scripts

### ISSUE THREAD

**Issue by bonham79** [CUNY-CL/yoyodyne#62]
More a reminder than a fix: we should keep up to date scripts for model architectures for quick testing and runs.

**Comment by kylebgorman** [comment]
I'm going to respectfully mark this as wontfix since we're just going to move to testing as documented in #5. Keeping these up to date proved basically impossible to me and added a data dependency to data we are not ready to release so these had to be removed before we went public. I am not terribly far away from completing #5, though, and can get back to it soon. I'm happy to share my personal test data and scripts as well---it's checked in privately.

**Comment by bonham79** [comment]
aight, would you kindly point me to the private scripts
